<?php
defined('BASEPATH') or exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
if (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') {

    $ht = "https://";
} else {
	$ht = "http://";
}
$config['base_url'] = $ht.$_SERVER['HTTP_HOST'];
$config['base_url'] .= preg_replace('@/+$@','',dirname($_SERVER['SCRIPT_NAME'])).'/'; 

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = true;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = 'vendor/autoload.php';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = false;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = true;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = false;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
// -------------------------------------------------------------------------
// SESSION HARDENING — SESS-001 Remediation
// -------------------------------------------------------------------------
// SECURITY CHANGE: Driver switched from 'files' to 'database'.
// Files stored in sys_get_temp_dir() (/tmp) are shared across all PHP
// workers in this Docker environment, creating a race condition where two
// concurrent requests can read each other's session data. The database
// driver uses atomic row-locking (SELECT ... FOR UPDATE in CI3's session
// library) which guarantees that each session row is accessed by exactly
// one request at a time, eliminating the cross-session bleed vector.
$config['sess_driver'] = 'database';

// The session cookie name remains unchanged to avoid breaking existing
// authenticated user sessions during a rolling deployment.
$config['sess_cookie_name'] = 'ci_session';

// SECURITY CHANGE: Expiration reduced from 7200 (2 hours) to 1800 (30
// minutes). A Super Admin session that was left open will now expire
// 30 minutes after the last activity, reducing the window of exposure
// from abandoned authenticated sessions.
$config['sess_expiration'] = 1800;

// SECURITY CHANGE: sess_save_path now points to the database table name
// 'ci_sessions'. CI3's Session_database driver uses this string as the
// table name. The table must exist — see the SQL schema comment below.
// Required table schema (run in your MariaDB hmssaas database):
//
//   CREATE TABLE IF NOT EXISTS `ci_sessions` (
//     `id`         varchar(128)         NOT NULL,
//     `ip_address` varchar(45)          NOT NULL,
//     `timestamp`  int(10) unsigned     DEFAULT 0 NOT NULL,
//     `data`       blob                 NOT NULL,
//     KEY `ci_sessions_timestamp` (`timestamp`)
//   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
//
$config['sess_save_path'] = 'ci_sessions';

// SECURITY CHANGE: sess_match_ip set to TRUE. This binds the session
// token to the IP address that created it. If an attacker steals the
// ci_session cookie (via network sniffing or XSS), the stolen cookie
// becomes invalid if used from a different IP address.
$config['sess_match_ip'] = TRUE;

// Session ID is rotated every 300 seconds (5 minutes) of activity.
// This limits the usefulness of any session token captured mid-session.
$config['sess_time_to_update'] = 300;

// SECURITY CHANGE: sess_regenerate_destroy set to TRUE.
// This is the primary fix for the Super Admin session bleed vulnerability.
// When CI3 auto-rotates the session ID (every sess_time_to_update seconds),
// it will now IMMEDIATELY DELETE the old session row from the database.
// Previously (when FALSE), old rows were left for the GC to clean up —
// during that window, two different clients could share the same session
// data if the file-based driver served a stale read.
$config['sess_regenerate_destroy'] = TRUE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
// =========================================================================
// COOKIE SECURITY HARDENING — COOK-001 Remediation (REGRESSION-001 Fixed)
// =========================================================================
//
// REGRESSION-001 ROOT CAUSE:
//   The previous patch set cookie_secure = TRUE unconditionally. The current
//   Docker stack (docker-compose.yml: ports 8080:80, php:8.1-apache with no
//   SSL module) serves plain HTTP. RFC 6265 mandates that browsers MUST
//   silently discard cookies carrying the Secure attribute when received over
//   a non-TLS connection. The result: the ci_session cookie is never stored,
//   every request appears as a new anonymous session, and no user can log in.
//
// SOLUTION — Multi-Signal TLS Detection:
//   We detect whether the current request is actually being served over a
//   secure channel using three independent signals, any one of which is
//   sufficient to confirm TLS:
//
//   SIGNAL 1: $_SERVER['HTTPS'] === 'on' (or any non-empty, non-'off' value)
//     Apache sets this when mod_ssl is active and the connection is TLS.
//     This is the canonical detection method for direct HTTPS serving.
//
//   SIGNAL 2: $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https'
//     An upstream Nginx/HAProxy reverse proxy that terminates TLS and
//     forwards traffic via plain HTTP to the Apache container sets this
//     header. Without this check, cookie_secure would fail even when the
//     end-user connection IS encrypted (the proxy-to-app leg is HTTP,
//     but the client-to-proxy leg is HTTPS).
//     SECURITY NOTE: This header must only be trusted if the application
//     is behind a known reverse proxy. In this Docker setup, the only
//     traffic source to port 80 of hms-web is either the host machine
//     (development) or a co-located proxy container (production). No
//     external actor can forge this header because port 80 is not exposed
//     to the internet directly.
//
//   SIGNAL 3: ENVIRONMENT === 'production'  AND  $CI_ENV is explicitly set
//     If a sysadmin sets CI_ENV=production in docker-compose.yml, we treat
//     it as a production deployment regardless of the other signals. This
//     provides a manual override for cases where the proxy doesn't set
//     X-Forwarded-Proto correctly.
//     IMPORTANT: The current Docker stack does NOT set CI_ENV, so this
//     signal is FALSE by default. It will only activate when the operator
//     deliberately sets it in the compose environment block.
//
// PRODUCTION SAFETY:
//   When any of the three signals is TRUE, cookie_secure is set to TRUE.
//   This means production deployments behind HTTPS (either direct or via
//   proxy) automatically receive the Secure cookie attribute.
//   Development deployments on plain HTTP receive cookie_secure = FALSE,
//   preserving full functionality without any manual config change.
// =========================================================================

// --- Signal 1: Direct HTTPS (Apache mod_ssl active) ---
$_tls_direct = (
    !empty($_SERVER['HTTPS']) &&
    strtolower($_SERVER['HTTPS']) !== 'off'
);

// --- Signal 2: Reverse-proxy TLS termination (Nginx → Apache HTTP tunnel) ---
// Normalize the header value to lowercase before comparison to handle
// proxies that send 'HTTPS', 'Https', or 'https' inconsistently.
$_tls_proxy = (
    isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
    strtolower(trim($_SERVER['HTTP_X_FORWARDED_PROTO'])) === 'https'
);

// --- Signal 3: Explicit production environment flag (operator override) ---
// isset($_SERVER['CI_ENV']) confirms the operator deliberately set CI_ENV
// rather than relying on the default fallback to 'production'. This
// prevents the default value in index.php (line 59) from accidentally
// enabling cookie_secure on a plain-HTTP development machine.
$_tls_env_flag = (
    isset($_SERVER['CI_ENV']) &&
    ENVIRONMENT === 'production'
);

// Compose the final cookie_secure value from all three signals.
// TRUE only when at least one signal confirms a secure transport layer.
$_is_secure_context = ($_tls_direct || $_tls_proxy || $_tls_env_flag);

// A namespaced prefix prevents collision with cookies from other
// applications potentially hosted on the same domain or origin.
$config['cookie_prefix']   = 'hms_';

// Set to empty string to scope the cookie to the current domain only.
// For multi-subdomain deployments (e.g., *.hospital.com), change to
// '.hospital.com'. Leave empty for single-domain installations.
$config['cookie_domain']   = '';

// Restrict cookie access to the application root path.
// This prevents cookies from being read by other applications on the
// same server that may share a different path under the same domain.
$config['cookie_path']     = '/';

// DYNAMIC SECURITY VALUE — resolved at runtime from the three signals above.
// TRUE  → cookie carries the Secure attribute → browser only sends over TLS
// FALSE → cookie sent over HTTP → safe for plain-HTTP development stacks
// No manual change required between development and production deployments.
$config['cookie_secure']   = $_is_secure_context;

// SECURITY CHANGE: cookie_httponly remains TRUE unconditionally.
// This flag is entirely independent of TLS. It prevents JavaScript from
// reading the session cookie (document.cookie), which is the primary
// defence against XSS-based session hijacking. There is no development
// scenario where exposing the session cookie to JavaScript is justified.
// This setting is NEVER conditional.
$config['cookie_httponly'] = TRUE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = false;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = false;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
// =========================================================================
// CSRF PROTECTION — CSRF-001 Remediation + REGRESSION-002 Fix
// =========================================================================
// Automatically protects all state-changing web methods while exempting
// the mobile API, and public-facing frontend/site controllers.
//
// csrf_protection  : Globally enabled. Every POST to a non-exempt URI must
//                    carry the hms_csrf_token field or CI3 returns HTTP 403.
// csrf_token_name  : Non-default name prevents trivial token enumeration.
// csrf_cookie_name : Cookie holding the server-side token value for compare.
// csrf_expire      : 900s (15 min). Limits stolen-token reuse window.
// csrf_regenerate  : TRUE — new token issued after every successful POST,
//                    preventing token-replay attacks.
//
// csrf_exclude_uris patterns (dual-form for rewrite-on and rewrite-off):
//   api/*         — Mobile REST API uses per-request credential auth.
//   frontend/*    — Public hospital booking forms inject tokens via
//                   form_open() at the HTML level.
//   site/*        — Public hospital profile pages. Same rationale.
$config['csrf_protection']  = TRUE;
$config['csrf_token_name']  = 'hms_csrf_token';
$config['csrf_cookie_name'] = 'hms_csrf_cookie';
$config['csrf_expire']      = 900;
$config['csrf_regenerate']  = TRUE;

$config['csrf_exclude_uris'] = array(
    'api/.*',
    'index\.php/api/.*',
    'frontend/.*',
    'index\.php/frontend/.*',
    'site/.*',
    'index\.php/site/.*',
);

// =========================================================================
// CORE ENGINE PREFERENCES
// =========================================================================
$config['compress_output']    = FALSE;
$config['time_reference']     = 'local';
$config['rewrite_short_tags'] = FALSE;
$config['proxy_ips']          = '';
